### ISSUE TITLE
Target Hardware Address is incorrect

### ISSUE THREAD

**Issue by cetfor** [dresende/node-arping#1]
Hello @dresende, thanks for the very cool module!

I was just checking it out and noticed that the ping method returns `packet.payload.payload.target_ha` which is the MAC of the system running the ARP ping, not the MAC of the responding system, which is `packet.payload.payload.sender_ha`.

For example, no matter which IP I scan `192.168.10.1`, `192.168.10.20`, etc. this module will always return `8c:85:90:58:97:84 responded in X.XXX secs`. `8c:85:90:58:97:84` is the MAC address for my MacBook's network interface. 

If I switch `target_ha` to `sender_ha` on the following line, everything works as expected.
https://github.com/dresende/node-arping/blob/1035634b6301257b81d95c10cad21a41d450d082/index.js#L165

I submitted a PR for this.

**Comment by dresende** [comment]
Fixed.
