### ISSUE TITLE
Pinging a host that isn't on the network results in an unhandled TypeError exception

### ISSUE THREAD

**Issue by cetfor** [dresende/node-arping#6]
This module works as expected when scanning IPs that are known to be listening on the network.  When you scan an IP that is not on the network, the module crashes with a TypeError in pcap2 session.js:124 (in pcap2 v3.0.4).

Consider the following script
```
const arp = require("arping");

function arpPing(ip) {
  arp.ping(ip, (err, info) => {
    if (err) throw err;
    console.log("%s - %s", ip, info.tha);
  });
}
```

We can very quickly scan live hosts on the network in succession.
```
arpPing("192.168.10.1");
arpPing("192.168.10.20");
arpPing("192.168.10.21");
arpPing("192.168.10.254");

192.168.10.1 - 60:73:5c:98:72:f3
192.168.10.20 - 00:0f:ff:58:1e:39
192.168.10.21 - 00:0f:ff:17:29:7a
192.168.10.254 - 00:0a:dd:03:4f:5a
```

But if we try to scan just a single host that isn't listening this happens.
```
arpPing("192.168.10.2");

/Users/john/Desktop/scratch/arp/node_modules/pcap2/lib/session.js:124
    return this.session.inject(data);
                        ^

TypeError: First argument must be a buffer
    at LiveSession.Session.inject (/Users/john/Desktop/scratch/arp/node_modules/pcap2/lib/session.js:124:25)
    at try_ping (/Users/john/Desktop/scratch/arp/node_modules/arping/index.js:172:10)
    at done (/Users/john/Desktop/scratch/arp/node_modules/arping/index.js:144:11)
    at Timeout.setTimeout [as _onTimeout] (/Users/john/Desktop/scratch/arp/node_modules/arping/index.js:179:3)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
```

I'm looking into this issue.  I'll submit a PR for it once I track it down but I probably won't get to it until next week.

**Comment by cetfor** [comment]
Ah ok, this happens when the module attempts to retry a ping due to a timeout.  The location of this issue is [here on line 144 in index.js](https://github.com/dresende/node-arping/blob/master/index.js#L144). 

The line:
```
return try_ping(packet, options, next);
```

Should be:
```
return try_ping(ip_address, packet, options, next);
```

By default, the module is configured to to retry a scan 3 times waiting 1 second between tries.
```
// from index.js
	try_ping(ip_address, packet, {
		tries    : options.tries    ||    3,
		interval : options.interval || 1000,
	}, next);
```

This this correction in place, after 3 attempts a Timeout error will be raised.

**Comment by dresende** [comment]
Thank you so much :)
